export const FETCH_WORKERS = "FETCH_WORKERS";
export const FETCH_WORKERS_SUCCESS = "FETCH_WORKERS_SUCCESS";
export const FETCH_WORKERS_FAILURE = "FETCH_WORKERS_FAILURE";

export const UPDATE_WORKER = "UPDATE_WORKER";
export const UPDATE_WORKER_SUCCESS = "UPDATE_WORKER_SUCCESS";
export const UPDATE_WORKER_FAILURE = "UPDATE_WORKER_FAILURE";

export const DELETE_WORKER = "DELETE_WORKER";
export const DELETE_WORKER_SUCCESS = "DELETE_WORKER_SUCCESS";
export const DELETE_WORKER_FAILURE = "DELETE_WORKER_FAILURE";

export const ADD_WORKER = "ADD_WORKER";
export const ADD_WORKER_SUCCESS = "ADD_WORKER_SUCCESS";
export const ADD_WORKER_FAILURE = "ADD_WORKER_FAILURE";
